### ISSUE TITLE
error with using the GUESSmyLT.py

### ISSUE THREAD

**Issue by mistrm82** [NBISweden/GUESSmyLT#10]
I tried following instruction but I keep getting the following:

`(base) Meetas-MacBook-Pro:GUESSmyLT mem205$ python GUESSmyLT.py 
Traceback (most recent call last):
  File "GUESSmyLT.py", line 12, in <module>
    from BCBio import GF`

**Comment by viklund** [comment]
Did you manage to install the software with `python setup.py install`? I wonder because it should be run with the command:

```bash
$ GUESSmyLT
```

i.e. without explicitly specifying the `python` executable or the `.py` fileending.

**Comment by mistrm82** [comment]
I did try the `python setup.py install` but wasn't very successful.

Are we able to run it without the setup install? If not, I can post the error from my setup install.

**Comment by Juke34** [comment]
Hi,
you will not be able to use it without installing it successfully with the `python setup.py install` command.
Please copy paste the error message you get from this command .

**Comment by mistrm82** [comment]
I was able to install successfully. I had to create a conda environment for all the dependencies/pre-requisites thanks!

Just a note that in your README it states:

> Installation using setup.py is not necessary, it adds the ability to run the tool using the command 'GUESSmyLT' globally. Tool can be used by running the python script 'GUESSmyLT.py' from within the tool folder. 

To me that suggests we do not need to `setup.oy` install , so perhaps remove or modify that? Also, this is not available for install on a Mac is that correct?

**Comment by Juke34** [comment]
Thank you for the feedback indeed this statement is wrong we will remove it from the readme. Apparently there is other things to update in the readme. E.g the Busco set is automatically download while we say that is had to be done by the user.
It can run on Mac the only problem is that version of Trinity from conda doesn’t work on Mac. So it has to be installed by another way.
