### ISSUE TITLE
cannot run with only fastq file

### ISSUE THREAD

**Issue by mistrm82** [NBISweden/GUESSmyLT#11]
The README says that we can run with only fastq files but I am unable to do so:

`GUESSmyLT --reads raw_fastq/Mov10_oe_1.subset.fq `

`Mode parameter (--mode) must be filled when no annotation provided (--annotation). It must be <genome> or <transcriptome>.`

**Comment by Juke34** [comment]
As suggested by the message it is missing the ‘—mode’ option. Just add ‘—mode genome’ and it should work fine.(launching the tool like that require trinity to be installed)

**Comment by Juke34** [comment]
I parameter is now optional, I have put 'genome' as default
