### ISSUE TITLE
Provide a docker container

### ISSUE THREAD

**Issue by jpfeil** [NBISweden/GUESSmyLT#13]
Do you have any interest in packaging this tool and all of its dependencies in a docker container? It would be a lot easier to deploy across computing environments.

**Comment by Juke34** [comment]
Hello,
Thank you for your interest in GUESSmyLT.
Bioconda provides a docker container for all their recipes. Have a look here: http://bioconda.github.io/recipes/guessmylt/README.html

You can access the docker container like that: 

> docker pull quay.io/biocontainers/guessmylt:0.2.5--py_0
