### ISSUE TITLE
result interpretation

### ISSUE THREAD

**Issue by Homap** [NBISweden/GUESSmyLT#15]
Hi,

I get the following result when running guessmylty:

fr_firststrand 43.3%
fr_secondstrand 0.4%
rf_secondstrand 1.4%
undecided 55.0%

More than half of the reads are undecided. I was wondering how could I interpret the results concerning the strandedness of the library?

Thank you,
Kind regards,
Homa

**Comment by Juke34** [comment]
Hi, it is clearly fr_firststrand. There is many reasons a read could end up in the undecided part, but the idea is to focus only on reads that have a clear signal. Nevertheless I agree that the high proportion of undecided might be dubious. I will try to have a look

**Comment by Homap** [comment]
Hi again, 

Just to say I got the library prep information and indeed, the dUTP protocol has been used, meaning data are fr_firststrand as indicated by GUESSmyLT.

Thanks again for your help,
Homa

**Comment by Juke34** [comment]
Thank you for your feedback.
