### ISSUE TITLE
Error. No genes could be found in --annotation

### ISSUE THREAD

**Issue by LehmannN** [NBISweden/GUESSmyLT#16]
Hello, 

I get the error ''Error. No genes could be found in --annotation" when specifying a GTF or GFF3 file. I know I could just run BUSCO but I would like to use the annotations I have. Could you please: 
1- Confirm you need GFF3 file ? 
2- That you need "gene" features in the GFF3 ? I have data from UCSC and we have those features (but no "gene"):
3UTR
5UTR
CDS
exon
start_codon
stop_codon
transcript

If I really need these 'genes features' do you know of any tool I could use to infer them ?

Thanks in advance,
 
N. Lehmann

**Comment by Juke34** [comment]
GUESSmyLT needs the `gene` feature.
Use [AGAT](https://github.com/NBISweden/AGAT) if you want to properly add those features. (agat_convert_sp_gxf2gxf.pl).
Otherwise with a sed command replacing `transcript` by `gene` should work.

**Comment by LehmannN** [comment]
Thanks ! Sorry I didn't see your message earlier. I fixed this little issue with `gffread --keep-genes input.gtf -o- > output.gff` (see https://github.com/gpertea/gffread/issues/54). Now I know I can do it also with AGAT :)

**Comment by Juke34** [comment]
I just checked the output from gffread you lost features... maybe it is the reason why your conversion to bigGenePred does not work:

Before convertion:  
3utr	54242	78821.52	1453.15
5utr	86473	25816.80	298.55
cds	669409	108378.01	161.90
exon	796527	264970.97	332.66
start_codon	49741	148.88	2.99
stop_codon	49735	148.87	2.99
transcript	62170	2960374.90	47617.42
Total	1768297	3438659.94	1944.62


after conversion:  
Type (3rd column)	Number	Size total (kb)	Size mean (bp)	/!\Results are rounding to two decimal places 
cds	669634	108526.88	162.07
exon	796527	264970.97	332.66
gene	23726	1152246.04	48564.70
transcript	62170	2960374.90	47617.42
Total	1552057	4486118.78	2890.43

With AGAT you should keep those features. Give it a try, maybe it will fix your problem

**Comment by LehmannN** [comment]
Ahah, thanks ! Will try now :)
