### ISSUE TITLE
hmmsearch Parse failed ...

### ISSUE THREAD

**Issue by papelypluma** [NBISweden/GUESSmyLT#18]
Hi GuessmyLT developers, I'd like to ask if [hmmsearch] Parse failed ... [hmmsearch] Line 2: illegal character % is something that can be safely ignored. I'm running the strand prediction with bam files. Although the job doesn't terminate with this INFO, I'm wondering if this has something to do with the hmmer version (using v3.3.2) or with input file. Thank you!

**Comment by Juke34** [comment]
It sounds like the protein fasta file analyzed by hmmsearch has character which are not expected in sequences. Might be due to empty protein sequence. I think I have seen that somewhere (case proteinY in the example below):

```
>Header proteinX
MLRSLT...
>Header proteinY

>Header proteinZ
MLRSLT...
```

You might check and edit the protein file directly in the Busco output folder.

**Comment by papelypluma** [comment]
Hi @Juke34 thanks for the pointers. I've found that the */augustus_output/extracted_proteins/*.faa.1 has this "Evidence%CDSCDS5'UTR3'UTRhintincompatible" trailing string in the sequence. I can edit the fasta files to get rid of this, but I was wondering if there's a way to address this on the fly - while GUESSmyLT is running so this warning doesn't appear. Quite a number of the sequences have this string of characters appended at the 3'-end.

**Comment by Juke34** [comment]
The problem is not related to GUESSmyLT itself but rather The version of Busco or related dependencies like Augustus. Try to upgrade or downgrade Augustus to see if it fix the problem. Could you share the
Version of busco and Augustus you are using?

**Comment by papelypluma** [comment]
Hi @Juke34, I'm using augustus 3.4.0 and busco 3.0.2.

**Comment by papelypluma** [comment]
Hi @Juke34. Just wondering if there's a prescribed version of Augustus to run with the guessmylt. I've tried varying busco versions and augustus (3.3.2 and 3.3.3), but to no avail the error still comes out. Thank you.

**Comment by Juke34** [comment]
It has been developed with busco 3.0.2

**Comment by papelypluma** [comment]
Thanks @Juke34 for the advice. Will try these versions.

**Comment by papelypluma** [comment]
Hi @Juke34 thanks for the help! You were right, it had to be augustus-3.2.3 and busco 3.0.2. That managed to address the issue. I'm also quoting the hmmer version I'm using is v3.3.2 for those that might run into the same/similar issue. Thanks a lot! Closing this issue now.
