### ISSUE TITLE
Samtools version check for sort command fails, tries to use `-f`

### ISSUE THREAD

**Issue by Shellfishgene** [NBISweden/GUESSmyLT#22]
I installed via Conda. The fix introduced in a4de3e0 does not work for me, it uses `-f` for output despite samtools version 1.14. Maybe [this](https://github.com/NBISweden/GUESSmyLT/blob/260ef92815f60a9e9610d176b2e4184c99c66bf6/GUESSmyLT/samtools#L28) line does not work for versions with double digit minor numbers? Probably best to remove support for ancient samtools versions and just use `-o`.

**Comment by Shellfishgene** [comment]
Never mind, duplicate of #17, didn't see that one because of not very descriptive issue name ;).

**Comment by Juke34** [comment]
If you use the testversion branch let me know if the issue is solved, lile that I can merge in master branch
